services:
  front-talkmaster:
    container_name: "front-talkmaster"
    build:
      context: .
      dockerfile: docker/front.prod.dockerfile
    ports:
      - "${FORWARD_FRONT_PORT:-5442}:80"
    networks:
      - talkmaster
      - hosted
    depends_on:
      - back-talkmaster
      - postgres-talkmaster
      - redis-talkmaster
  back-talkmaster:
    container_name: "back-talkmaster"
    #user: www-data
    build:
      context: .
      dockerfile: docker/php/prod.final.Dockerfile
    environment:
      IGNITION_LOCAL_SITES_PATH: "${PWD:-/var/www/html}"
    volumes:
      - "./back/:/var/www/html"
      - laravel-storage:/var/www/html/storage
    networks:
      - talkmaster
    depends_on:
      - postgres-talkmaster
      - redis-talkmaster
  postgres-talkmaster:
    image: "postgres:15"
    container_name: postgres-talkmaster
    #ports:
    #  - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME:-talkmaster}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
      POSTGRES_DB: "${DB_DATABASE:-talkmaster_database}"
    volumes:
      - "postgres-talkmaster:/var/lib/postgresql/data"
    networks:
      - talkmaster
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME:-talkmaster}"]
      retries: 3
      timeout: 5s
  redis-talkmaster:
    container_name: "redis-talkmaster"
    image: "redis:alpine"
    #ports:
    #  - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "redis-talkmaster:/data"
    networks:
      - talkmaster
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  nginx-talkmaster:
    image: nginx:stable-alpine
    container_name: nginx-talkmaster
    depends_on:
      - back-talkmaster
    #ports:
    ##  - "8080:8080"
    volumes:
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf:ro
      - ./back:/var/www/html:ro
    networks:
      - talkmaster

networks:
  talkmaster:
    driver: bridge
  hosted:
    external: true

volumes:
  postgres-talkmaster:
    driver: local
  redis-talkmaster:
    driver: local
  laravel-storage:
    driver: local
