name: Deploying to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build and expose
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build the compose
        run: |
          docker compose -f prod.docker-compose.yml up -d --build --remove-orphans
