name: Deploying to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build and expose
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get ENV
        run: |
          echo "${{ secrets.BACKEND_ENV }}" > ./back/.env
      - name: Build the compose
        run: |
          docker compose -f prod.docker-compose.yml build --no-cache
          docker compose -f prod.docker-compose.yml up -d
