name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  laravel-ci:
    name: Laravel CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, pdo, tokenizer, xml, ctype, fileinfo
          coverage: none

      - name: Install dependencies
        working-directory: ./back
        run: composer install --prefer-dist --no-progress

      - name: Setup environment
        working-directory: ./back
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Pint linter (check only)
        working-directory: ./back
        run: ./vendor/bin/pint --verbose --test --dirty

      - name: Run Larastan (PHPStan)
        working-directory: ./back
        run: ./vendor/bin/phpstan analyse --memory-limit=4G

      - name: Run PHPUnit tests
        working-directory: ./back
        run: ./vendor/bin/phpunit
