name: Publish Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'front/**'
      - 'back/**'
      - 'prod.docker-compose.yml'
      - 'docker-compose.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push ${{ matrix.name }} image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: front
            context: .
            dockerfile: docker/front.Dockerfile
            image_suffix: front
          - name: back
            context: docker/php
            dockerfile: prod.Dockerfile
            image_suffix: back
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Extract Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-${{ matrix.image_suffix }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: int128/kaniko-action@v1
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache/${{ matrix.image_suffix }}
